[package]
name = "obfs4-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arti-client = { git = "https://gitlab.torproject.org/tpo/core/arti/", features = [ "bridge-client", "pt-client", "experimental" ] }
tor-chanmgr = { git = "https://gitlab.torproject.org/tpo/core/arti/" , features = [ "pt-client", "experimental-api" ]}
tor-guardmgr = { git = "https://gitlab.torproject.org/tpo/core/arti/" , features = [ "full" ]}
tokio = { version = "1.7", features = ["full"] }
tracing = "0.1"
tor-rtcompat = { git = "https://gitlab.torproject.org/tpo/core/arti/" }
tracing-subscriber = "0.2.0"
tls-api = "0.9.0"
tls-api-native-tls = "0.9.0"
tor-error = { git = "https://gitlab.torproject.org/tpo/core/arti/" }
futures = "0.3.28"
serde = "1.0.180"
axum = "0.6.19"
serde_json = "1.0.104"
chrono = "0.4.26"